# Generated by Django 4.2.5 on 2023-09-27 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0015_alter_profile_first_name_alter_profile_last_name'),
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.CharField(choices=[('0', 'Unread'), ('1', 'Read')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='app_main.profile'),
        ),
    ]
