# Generated by Django 4.2.5 on 2023-09-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_message_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='fullname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
