# Generated by Django 4.2.5 on 2023-10-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0005_alter_message_email_alter_message_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
