# Generated by Django 4.2.3 on 2023-08-02 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0009_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(default='Deleted account', on_delete=django.db.models.deletion.SET_DEFAULT, to='app_main.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.project')),
            ],
        ),
    ]
