# Generated by Django 4.2.4 on 2023-08-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0014_alter_project_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
