# Generated by Django 4.2.5 on 2023-10-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0015_alter_profile_first_name_alter_profile_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='devsearch-test/profiles/user-default.png', null=True, upload_to='devsearch-test/profiles/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='devsearch-test/projects/project-default.jpg', null=True, upload_to='devsearch-test/projects/'),
        ),
    ]
